### PR TITLE
Add slather/Coveralls test coverage reports

### PR DESCRIPTION
**Pull request by dasmer**
- Modify project file to generate code coverage metrics
- Add step to .travis.yml to install slather and send metrics to Coveralls
- Add .slather.yml to configure how we send metrics to Coveralls.
- Add Coveralls Badge to `README.md`

You will need to enable Coveralls for AlexDenisov/FrameAccessor. I ran slather locally and reported test coverage is 100% :star2:

### CODE REVIEW

**Comment by AlexDenisov** [comment]
Very nice feature, thank you @dasmer.
I didn't manage to find why coveralls needs commit access, maybe you can give me a point?
I'm pretty sure there is something obvious, but I can't blindly give an access to a third-party tool, 'cause I'm member of a few organizations with a bunch of private repos.

**Comment by dasmer** [comment]
@AlexDenisov I would refer to https://github.com/lemurheavy/coveralls-public/issues/450. I believe Coveralls needs `commit:status` to generate coverage stats. I would defer to @nickmerwin for more info.

**Comment by dasmer** [comment]
It looks like test coverage isn't being reported correctly on Travis. Closing until I figure out why.

**Comment by AlexDenisov** [comment]
Got it, let me know if I can help you.

**Comment by dasmer** [comment]
Re-opening to test a fix

**Comment by dasmer** [comment]
@AlexDenisov: We're getting coverage reports again :dancer: 

[Coverage Status](https://coveralls.io/r/dasmer/FrameAccessor?branch=daz%2Fslather)

**Comment by dasmer** [comment]
Also, to give you some more insight on why coveralls.io asks for commit read access, the service gives you line-by-line data on how often a tested line is called on in your unit tests:

ie:
screen shot 2015-04-22 at 10 06 12 pm

**Comment by AlexDenisov** [comment]
Great job, @dasmer!
Waiting for a travis build to see the new and shiny coveralls badge :+1:

**Comment by MaximDzhezhelo** [comment]
Very good job)

**Pull request merged**
