### PR TITLE
add view point

### PR DESCRIPTION
**Pull request by 804145113**
Access to the view of four Angle coordinate

### CODE REVIEW

**Comment by AlexDenisov** [comment]
Hi @804145113,
thank you for contribution, could you please update `README`?

**Comment by 804145113** [comment]
Yes

**Comment by AlexDenisov** [comment]
@804145113 great!
Could yo please squash these commits into one?
Here is very good reading, just fyi: http://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by 804145113** [comment]
Could you please close  this conversation? I submitted a new conversation！

**Pull request closed without merging**
